// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy69DKrtSA4xkjzajOP95orvHxLzwgY3U',
    appId: '1:300381764872:web:1897803db59989ed9540bd',
    messagingSenderId: '300381764872',
    projectId: 'lexbid-ai',
    authDomain: 'lexbid-ai.firebaseapp.com',
    storageBucket: 'lexbid-ai.firebasestorage.app',
    measurementId: 'G-3JC5RQVH3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbSqUCWuz_ojcmpI8u2OjmdAT7Dw5dflY',
    appId: '1:300381764872:android:253c639b3f02d6479540bd',
    messagingSenderId: '300381764872',
    projectId: 'lexbid-ai',
    storageBucket: 'lexbid-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHm3oyAv-kPnXpf6v_UPuPU9VQI-OfftA',
    appId: '1:300381764872:ios:3a36727041012bb69540bd',
    messagingSenderId: '300381764872',
    projectId: 'lexbid-ai',
    storageBucket: 'lexbid-ai.firebasestorage.app',
    iosBundleId: 'com.example.lexbid',
  );
}
